print("Belajar Python menyenangkan")
print(100)
print(3.14)
print("Nilai Pi:", 3.14)
print(10 + 5)
print(20 - 8)
print(4 * 7)
print(15 / 4)
print(15 // 4)
print(15 % 4)
print(2 ** 8)
print("Senin", "Selasa", "Rabu")
print("Senin", "Selasa", "Rabu", sep=" | ")
print("Baris 1", end="")
print("  Baris 2 di baris yang sama")